services:
  db: 
    image: postgres
    env_file:
      - .db-production.env
    volumes:
      - ./storage/production/db:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .web-production.env
    command: bash -c "rm -rf tmp/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/ticweb-api
    ports: 
    - "3000:3000"
    depends_on:
      - db
