services:
  db: 
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: w^Y4SDjSn#SBjg1U
  web:
    build: .
    command: bash -c "rm -rf tmp/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/ticweb-api
    ports: 
    - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: w^Y4SDjSn#SBjg1U
    depends_on:
      - db
